export const services = [
  {
    slug: 'vending-machines',
    name: 'Traditional Vending Machines',
    shortName: 'Vending Machines',
    icon: '🥤',
    image: '/service_traditional_vending.png',
    tagline: 'The Classic — Fully Stocked, Always Fresh',
    description: 'Traditional vending machines remain the most popular workplace refreshment solution for NYC businesses. Modern cashless machines stocked with snacks, beverages, and fresh items — installed and maintained completely free of charge.',
    idealFor: '20–150 employees',
    installTime: '1–2 business days',
    features: [
      'Cashless payment — tap, swipe, or phone',
      '40–60 product slots, fully customizable',
      'Snacks, beverages, fresh food & frozen options',
      'Temperature-controlled for fresh items',
      '24/7 availability — no staff needed',
      'Remote monitoring & auto-restocking alerts',
      'ADA-compliant machines available',
      'Energy-efficient LED lighting',
    ],
    bestFor: [
      { type: 'Corporate Offices', reason: 'Keeps employees fueled between meetings without leaving the building.' },
      { type: 'Warehouses', reason: 'Shift workers need quick, accessible food options on the floor.' },
      { type: 'Medical Offices', reason: 'Staff lounges benefit from always-stocked refreshment options.' },
      { type: 'Schools', reason: 'Faculty rooms and student areas served separately if needed.' },
      { type: 'Auto Dealerships', reason: 'Keeps salespeople and service bay staff fueled all day.' },
    ],
    faqs: [
      { q: 'Do I need to pay anything upfront?', a: 'No. Installation, the machine itself, stocking, and all maintenance are provided at zero cost to your business.' },
      { q: 'How often is the machine restocked?', a: 'We monitor inventory remotely and restock before items run out — typically 1–3 times per week depending on usage.' },
      { q: 'Can we choose what products are stocked?', a: 'Absolutely. We work with you to customize the product mix based on your team\'s preferences. You can request changes at any time.' },
      { q: 'What if the machine breaks down?', a: 'Our local NYC service team responds same day or next business day for all repairs. Downtime is minimized.' },
      { q: 'Is there a contract?', a: 'No long-term contracts. We operate on a flexible arrangement — you can end the service with reasonable notice if needed.' },
    ],
  },
  {
    slug: 'ai-vending',
    name: 'AI Smart Vending Machines',
    shortName: 'AI Smart Vending',
    icon: '🤖',
    image: '/service_ai_vending.png',
    tagline: 'Next-Generation Vending Powered by AI',
    description: 'AI smart vending machines bring retail-grade technology to your NYC breakroom. Computer vision identifies products, touchscreen menus browse inventory, and machine learning tracks purchase patterns to predict what your team wants before they run out.',
    idealFor: '30–200+ employees',
    installTime: '2–3 business days',
    features: [
      'Computer vision — no barcode scanning needed',
      'Large touchscreen product browser with photos',
      'AI demand prediction — right products, always',
      'Real-time inventory dashboard for management',
      'Full dietary info, allergen labels on screen',
      'Cashless, contactless, and app-based payment',
      'Adjustable temperature zones in one unit',
      'Analytics reports on consumption patterns',
    ],
    bestFor: [
      { type: 'Tech Companies', reason: 'Tech-forward teams appreciate modern, data-driven amenities.' },
      { type: 'Corporate HQs', reason: 'Flagship offices deserve flagship vending technology.' },
      { type: 'Medical Facilities', reason: 'Allergen and nutrition data on-screen is valuable for health-conscious teams.' },
      { type: 'Call Centers', reason: 'High-volume usage benefits from AI inventory prediction.' },
      { type: 'Hotels & Hospitality', reason: 'Guest-facing AI machines elevate the property experience.' },
    ],
    faqs: [
      { q: 'How does the AI actually work?', a: 'Cameras inside the machine recognize what you take out (no scanning required), charge your account, and log the data. The system learns which items sell fastest and adjusts restocking priorities automatically.' },
      { q: 'Is it more expensive than a regular machine?', a: 'Not for you — it\'s still completely free. The AI machines cost more to operate on our end, but we offer them at the same zero-cost model because higher-usage locations justify it.' },
      { q: 'What payment methods work?', a: 'Credit/debit cards, Apple Pay, Google Pay, and employee app accounts with prepaid balances.' },
      { q: 'Can employees see nutrition information?', a: 'Yes — full nutrition facts, ingredients, and allergen warnings are shown on the touchscreen for every product.' },
    ],
  },
  {
    slug: 'micro-markets',
    name: 'Micro Markets',
    shortName: 'Micro Markets',
    icon: '🏪',
    image: '/service_micro_market.png',
    tagline: 'A Mini Convenience Store in Your Breakroom',
    description: 'Micro markets transform any break room into an open-format mini market with open shelving, a walk-in cooler, and a self-checkout kiosk. Your team browses and grabs what they want — no machine, no buttons, just a real retail experience inside your office.',
    idealFor: '50–500+ employees',
    installTime: '3–5 business days',
    features: [
      '200–400+ product selections (vs 40 in vending)',
      'Open shelving — browse like a real store',
      'Walk-in cooler for fresh food, drinks, meals',
      'Self-checkout kiosk — card, phone, or account',
      'Hot food station option available',
      'Employee account system with payroll deduction option',
      'Subsidized pricing option — you set the discount',
      'Custom branding and signage available',
    ],
    bestFor: [
      { type: 'Large Offices (50+)', reason: 'High traffic justifies the larger footprint and variety.' },
      { type: 'Corporate Campuses', reason: 'Multiple micro markets across a campus replace cafeteria costs.' },
      { type: 'Warehouses & Distribution', reason: 'Large teams need full meal options, not just snacks.' },
      { type: 'Hotels', reason: 'Lobby micro markets serve guests 24/7 without staffing.' },
      { type: 'Universities', reason: 'Student and faculty buildings benefit from always-open market access.' },
    ],
    faqs: [
      { q: 'How much space does a micro market need?', a: 'We can work with as little as 100–150 square feet for a compact setup. A full micro market with cooler and shelving typically needs 150–250 sq ft.' },
      { q: 'What about theft?', a: 'Micro markets have an excellent track record. The self-checkout kiosk and optional camera systems create accountability. Shrinkage rates are typically under 1%.' },
      { q: 'Can employees pay with their company ID?', a: 'Yes — we can set up employee account cards or app-based accounts that tie to a badge or ID number, with optional payroll deduction.' },
      { q: 'Can the company subsidize pricing for employees?', a: 'Absolutely. Many NYC employers subsidize 25–100% of the cost as an employee perk. We handle the billing directly.' },
    ],
  },
  {
    slug: 'coffee-services',
    name: 'Office Coffee Services',
    shortName: 'Coffee Services',
    icon: '☕',
    image: '/service_coffee.png',
    tagline: 'Café-Quality Coffee in Your NYC Office',
    description: 'From single-serve Keurig-style stations to full bean-to-cup espresso machines, we provide complete coffee service for New York City offices. Equipment, supplies, maintenance, and restocking — all included at no cost to qualifying businesses.',
    idealFor: '15–300+ employees',
    installTime: '1–2 business days',
    features: [
      'Bean-to-cup espresso machines — café quality',
      'Single-serve pod systems for smaller teams',
      'Full coffee, tea, and hot chocolate selection',
      'Branded cup options available',
      'Milk, creamer, sugar, and condiment service',
      'Weekly supplies delivery (pods, beans, cups)',
      'Machine maintenance and deep cleaning included',
      'Optional cold brew and iced beverage systems',
    ],
    bestFor: [
      { type: 'Professional Services', reason: 'Law firms, finance, and consulting offices depend on quality coffee for long hours.' },
      { type: 'Creative Agencies', reason: 'Coffee is fuel for creative work — quality matters.' },
      { type: 'Tech Offices', reason: 'A strong coffee program is a top-10 office perk for tech workers.' },
      { type: 'Medical Offices', reason: 'Staff rooms benefit from reliable, always-stocked coffee service.' },
      { type: 'Co-working Spaces', reason: 'Coffee stations are a key amenity for member retention.' },
    ],
    faqs: [
      { q: 'What coffee brands do you stock?', a: 'We work with a range of suppliers including premium NYC roasters. We\'ll match brands to your team\'s preferences.' },
      { q: 'Do we need plumbing installed?', a: 'Most machines connect to a standard water line. For offices without close water access, we also offer tank-fed systems that just need power.' },
      { q: 'How often are supplies restocked?', a: 'We deliver pods, beans, cups, and condiments on a regular schedule based on your team\'s usage — typically weekly or biweekly.' },
      { q: 'Can we have both a coffee machine and a vending machine?', a: 'Absolutely — most of our NYC clients use both. Coffee in the main break room and a vending machine for snacks and cold drinks.' },
    ],
  },
  {
    slug: 'pantry-services',
    name: 'Office Pantry Services',
    shortName: 'Pantry Services',
    icon: '🍎',
    image: '/service_pantry.png',
    tagline: 'A Fully Stocked Pantry for Your Team',
    description: 'Office pantry service brings a curated selection of snacks, fresh fruit, beverages, and breakfast items directly to your kitchen or break room shelves. Unlike vending, pantry items are freely accessible — we stock, you enjoy.',
    idealFor: '25–200 employees',
    installTime: '2–3 days for first delivery',
    features: [
      'Open pantry — no machine, no payment needed',
      'Fresh fruit delivery (optional)',
      'Healthy snack selections: nuts, bars, jerky, etc.',
      'Breakfast items: yogurt, granola, oatmeal',
      'Beverages: sparkling water, juice, energy drinks',
      'Fully customizable menu — you choose the items',
      'Weekly or biweekly delivery schedule',
      'Eco-friendly packaging options available',
    ],
    bestFor: [
      { type: 'Startups & Growth Companies', reason: 'Free snacks are a high-impact, low-cost employee perk for fast-growing teams.' },
      { type: 'Professional Services', reason: 'Stocked pantries keep staff in the office and productive.' },
      { type: 'Co-working Operators', reason: 'Member pantry access is a premium amenity that drives retention.' },
      { type: 'Media & Advertising', reason: 'Long shoot days and edit sessions require accessible fuel.' },
      { type: 'Tech Offices', reason: 'Pantry perks rank consistently high in employee satisfaction surveys.' },
    ],
    faqs: [
      { q: 'Is the pantry service really free?', a: 'Yes — for qualifying businesses. The pantry model works similarly to vending: we provide the service and make our margin on the products. No cost to the business.' },
      { q: 'How is pantry different from a vending machine?', a: 'Pantry items sit on open shelves, freely accessible. No payment required per item. It\'s an employer-provided perk rather than a pay-to-eat model.' },
      { q: 'Can we mix pantry and vending?', a: 'Absolutely. Many NYC offices use pantry service for healthy snacks and breakfast items, with a vending machine for beverages and indulgent options.' },
      { q: 'What if we want to add or remove products?', a: 'Just let us know. We update your product list with 48 hours notice for the next delivery.' },
    ],
  },
  {
    slug: 'custom-solutions',
    name: 'Custom Vending Solutions',
    shortName: 'Custom Solutions',
    icon: '⚙️',
    image: '/service_custom.png',
    tagline: 'Built Around Your Business',
    description: 'Not every NYC business fits a standard template. We design custom vending and refreshment solutions for unique spaces — multi-floor offices, large corporate campuses, hotels, hospitals, universities, and specialty environments that need a tailored approach.',
    idealFor: 'Any size — custom scoped',
    installTime: 'Varies by scope',
    features: [
      'Multi-machine deployments across multiple floors',
      'Mixed service types — vending + micro market + coffee',
      'Custom product menus per department or floor',
      'White-label branding on machines and kiosks',
      'Dedicated account manager for large accounts',
      'Custom reporting and analytics dashboard',
      'Payroll deduction and employee account systems',
      'Scheduled service windows for secure facilities',
    ],
    bestFor: [
      { type: 'Corporate Campuses', reason: 'Multiple buildings and floors need coordinated multi-machine deployment.' },
      { type: 'Hospitals & Medical Centers', reason: 'Secure floors, staff lounges, and waiting areas all have different needs.' },
      { type: 'Universities', reason: 'Dorms, libraries, admin buildings, and sports facilities each need custom service.' },
      { type: 'Hotels & Resorts', reason: 'Guest floors, staff areas, conference centers, and pool decks all benefit from different setups.' },
      { type: 'Government Facilities', reason: 'Security requirements, access restrictions, and compliance needs require a custom approach.' },
    ],
    faqs: [
      { q: 'How do we start with a custom solution?', a: 'It starts with a free site consultation. We visit your location, map out all the spaces, understand your needs, and propose a full solution — no obligation.' },
      { q: 'Can you handle multiple locations across NYC?', a: 'Yes — we service all five boroughs and can coordinate multi-location contracts for businesses with multiple NYC sites.' },
      { q: 'What\'s the minimum size for a custom engagement?', a: 'There\'s no hard minimum. We\'ve designed custom solutions for 50-person companies and 2,000-person campuses. It depends on the complexity of your needs, not just headcount.' },
    ],
  },
]
